apiVersion: 1

datasources:
  - name: InfluxDB-Groceries
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: groceries
      defaultBucket: groceries
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN:-my-super-secret-grocery-token}
    isDefault: true
    editable: true
